Clarify and reference spinbit optional/version; fixes #179
quicwg/ops-drafts pull request #221
Opened 2021-02-12 12:36 UTC by britram

2021-02-12 12:45 UTC, britram commented
fix #179

2021-02-15 16:31 UTC, mirjak approved these changes

2021-02-15 16:36 UTC, mirjak requested changes

2021-02-15 16:36 UTC, mirjak commented on draft-ietf-quic-manageability.md
>  The spin bit provides an additional method to measure per-flow RTT from
```suggestion
The spin bit provides an additional version-specific method (see section 17.4 of {{?QUIC-TRANSPORT}}) to measure per-flow RTT from
```

2021-02-15 16:36 UTC, mirjak commented on draft-ietf-quic-manageability.md
> +Endpoint participation in spin bit signaling is optional and version-specific
```suggestion
Endpoint participation in spin bit signaling is optional. That is, while
```

2021-02-15 16:36 UTC, mirjak commented on draft-ietf-quic-manageability.md
> +(see section 17.4 of {{?QUIC-TRANSPORT}}). That is, while
```suggestion
```

2021-02-22 10:35 UTC, merged